#!/bin/sh

# newpart

# Create a new partition on the given device (argument $1)
# $2 - start position (MB)
# $3 - end position (MB)
# $4 - fstype (ext2/linux-swap/...)
# $5 - primary/logical
if parted -s $1 unit MB mkpart $5 $4 $2 $3; then
    echo -n '^OK^'
echo
    echo -n "Couldn't create partition on $1 from $2 MB to $3 MB"
fi
