#! /bin/sh
# do-mkinitcpio  - Regenerate the initramfs for the new system

# It would be possible to edit the initcpio configs, after which
# the images would have to be regenerated, but it is not so easy
# to know what the desired result is (whether pata or ide) and,
# for the mkinitcpio call, which kernel is affected, i.e. which
# preset to use - though maybe there would only be one preset,
# which could also be found by grep.

INSTALL=/tmp/install

idir=${INSTALL}/etc/mkinitcpio.d
presets=$( ls ${idir} | grep "kernel.*\.preset" )

# I'm not at all sure about this, but I assume that only one of pata
# and ide is wanted, so if pata is in /etc/mkinitcpio.conf, I'll
# remove all ide entries, and vice versa.
if egrep "^HOOKS=.* pata" ${INSTALL}/etc/mkinitcpio.conf &>/dev/null; then
    nodisk=ide
else
    nodisk=pata
fi

for f in $( ls ${idir} | grep "\-fallback.conf" ); do
    sed -i "s|\(^HOOKS=.*\) ${nodisk}|\1|" ${idir}/${f}
done
cp -f ${INSTALL}/etc/mkinitcpio.conf ${INSTALL}/etc/mkinitcpio.conf.orig
sed -i "s|\(^HOOKS=.*\) ${nodisk}|\1|" ${INSTALL}/etc/mkinitcpio.conf

# For the mkinitcpio call there would probably need to be mount --bind
# calls for dev, proc and sys (taken from grub install script):

mount --bind /proc ${INSTALL}/proc
mount --bind /sys ${INSTALL}/sys
mount --bind /dev ${INSTALL}/dev

cat /proc/mounts | grep ${INSTALL} | sed "s|${INSTALL}|/|" | \
        sed "s|//|/|" >${INSTALL}/etc/mtab

for p in ${presets}; do
    chroot ${INSTALL} /sbin/mkinitcpio -p ${p%.preset}
done

:>${INSTALL}/etc/mtab

umount ${INSTALL}/dev
umount ${INSTALL}/sys
umount ${INSTALL}/proc
