#!/bin/bash

dialog --title "SHUTDOWN" --default-item 1 --menu "Choose action" 10 50 5 \
       1 "Turn computer off" 2 "Reboot" 2> /tmp/shutdown

resp=`cat /tmp/shutdown`

if [ "$resp" == "1" ]; then
    chvt 1 ; halt
elif [ "$resp" == "2" ]; then
    chvt 1 ; reboot
fi
