#!/bin/sh
# This script should be run (within the misc directory) to create a
# distributable larch packet, containing the actual larch package and
# a set-up script to make it usable without installing via pacman.

version=5.0.7

# Get path to this directory, via the location of this script
fullpath="$( readlink -f $0 )"
scriptdir="$( dirname ${fullpath} )"

# Just in case ...
cd ${scriptdir}


rm -rf larchpak
mkdir -p larchpak/larchpacks

if ! [ -f larch-*.pkg.tar.gz ]; then
    tar -czf larch-${version}.tar.gz -C .. larch
    sed -i "s|^pkgver=.*|pkgver=${version}|" PKGBUILD
    if ! makepkg; then exit 1; fi
fi
cp larch-*.pkg.tar.gz larchpak/larchpacks

cp larch-setup larchpak

echo ${version} >larchpak/VERSION

cat >larchpak/README <<EOT
You can set up larch for use from within this directory by running
'larch-setup', which will unpack the larch package and set up
symlinks to the main scripts.

Note that the larchpacks directory is needed when using 'mklarch', so
this packet might be the most convenient way to use it.

You can of course also install the larch package (in the 'larchpacks'
directory) using 'pacman -U'.
EOT

tar -czf larchpak-${version}.tar.gz larchpak
