#! /bin/sh
# larch-tidy  - Finish off copy part of installation

INSTALL=/tmp/install

# Make special directories
mkdir -m 1777 ${INSTALL}/tmp
mkdir ${INSTALL}/media
mkdir ${INSTALL}/sys
mkdir ${INSTALL}/proc

mkdir ${INSTALL}/mnt
find /mnt -maxdepth 1 -type d -exec mkdir ${INSTALL}/mnt/{} \;

mkdir ${INSTALL}/dev
mknod ${INSTALL}/dev/console c 5 1
mknod ${INSTALL}/dev/null c 1 3
mknod ${INSTALL}/dev/zero c 1 5

# Get these files in their 'original' versions
tar -xzf /.livesys/arch0.tar.gz -C ${INSTALL}

# Remove live-specific packages?
#for p in larch; do
#    pacman -r ${INSTALL} -R ${p} 2>/dev/null

