#!/bin/sh

# do-mount

# Mount a partition (argument $1) at mount point /tmp/install$2

if [ "$1" = "/" ]; then
    mount -o dev,exec $1 /tmp/install
else
    mount $1 /tmp/install$2
fi

if $?; then
    echo -n '^OK^'
fi
