#!/bin/sh

# get-usableparts

# Get a list of partitions which could, potentially be mounted.
# Return the device basename and a tag: '+' for removable, '-' for not

# Use sfdisk, because it's easier to get the ids out, but check the
# partitions against fdisk because sfdisk shows primary partitions
# even if they aren't allocated.
fdisk -l > /tmp/fdiskl

sfdisk -d | grep "^/dev/" | sed "s|\(.*\):.*Id=\(..\).*|\1 \2|" | \
    while read dev id; do
        # Ignore if id is "Extended" or "LVM", these are not usable partitions
        if [ "${id}" = "5" -o "${id}" = "8e" -o "${id}" = "82" ]; then
            continue
        fi
        if ! grep "^${dev} " /tmp/fdiskl &>/dev/null; then
            continue
        fi
        removable=""
        part=$( basename ${dev} )
        echo -n "${part}"
        if [ $( cat /sys/block/${part:0:3}/removable 2>/dev/null ) -ne 0 ]; then
            echo " +"
        else
            echo " -"
        fi
    done
