#!/bin/sh

# part1-resize

# Reduce the size of the first partition (type NTFS) on the given device
# (argument $1)

# $2 - start position (bytes)
# $3 - end position (bytes)

if parted -s $1 rm 1; then
    if parted -s $1 mkpart primary NTFS $2 $3; then
        echo -n '^OK^'
    fi
fi
