#!/bin/sh
# This script should be run (within the misc directory) to create a
# distributable larch packet, containing the actual larch package and
# a set-up script to make it usable without installing via pacman.

version=5.1.0

# Get path to this directory, via the location of this script
fullpath="$( readlink -f $0 )"
scriptdir="$( dirname ${fullpath} )"

# Just in case ...
cd ${scriptdir}

sed -i "s|^pkgver=.*|pkgver=${version}|" PKGBUILD
tar -czf larch-${version}.tar.gz -C .. larch larch-live larchin
makepkg

cat <<EOT
You can set up larch for use from within this directory by running
'larch-setup', which will unpack the larch package and set up
symlinks to the main scripts.

Or else you could copy the newly created larch*.pkg.tar.gz package, together
with the 'larch-setup' script, to a clean directory and run the latter there.

Alternatively, you can of course install the larch package using 'pacman -U'.
EOT
